apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBSRURBQ1RFRC1DRVJUSUZJQ0FURS0tLS0tCi4uLg==
    server: https://192.168.56.10:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBSRURBQ1RFRC1DRVJUSUZJQ0FURS0tLS0tCi4uLg==
    client-key-data: LS0tLS1CRUdJTiBSRURBQ1RFRC1QUklWQVRFLUtFWS0tLS0tCi4uLg==
